services:
  - type: web
    name: django-social-media
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn social_book.wsgi
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: social_book.settings
